Apply radiative boundary conditions to Z4c variables. Update schedule of TwoPuncturesX
EinsteinToolkit/SpacetimeX pull request #19
Opened 2023-10-20 16:05 UTC by jaykalinani

Apply radiative boundary conditions to Z4c variables using the new NewRadX thorn. 
Update schedule of TwoPuncturesX.

2023-10-25 19:01 UTC, eschnett requested changes

2023-10-25 19:01 UTC, eschnett commented on Z4c/interface.ccl
> +USES INCLUDE HEADER: newradx.hxx
Where does this header come from? Are you missing a `configuration.ccl` entry?

2023-10-25 19:01 UTC, eschnett commented on Z4c/param.ccl
> -
Why are you deleting these lines? They separate two groups of parameters.

2023-10-25 19:01 UTC, eschnett commented on Z4c/interface.ccl
Can you add another empty line here?

2023-10-25 19:01 UTC, eschnett commented on Z4c/schedule.ccl
> +SCHEDULE Z4c_apply_boundary_conditions IN ODESolvers_RHS AFTER Z4c_RHS
`Z4c_RHS` is not scheduled in `ODESolvers_RHS`. It's scheduled in a group `Z4c_RHSGroup`. You dependency (the `AFTER`) is not working.

2023-10-25 19:01 UTC, eschnett commented on Z4c/src/apply_newrad.cxx
> +using namespace Loop;
You are not using `Loop` nor `std` in this file.

2023-10-25 19:01 UTC, eschnett commented on Z4c/src/apply_newrad.cxx
> +#include "loop_device.hxx"
You don't need `loop_device.hxx` here.

2023-10-25 19:01 UTC, eschnett commented on Z4c/src/apply_newrad.cxx
> +#include "cctk.h"
We are using angle bracket `<>` everywhere else in this thorn, can you change this?

2023-10-25 19:01 UTC, eschnett commented on Z4c/param.ccl
> +  "none"      :: "use CarpetX default BCS"
`none` is a weird name for "use CarpetX default boundary conditions". Call it `CarpetX` instead?

2023-10-25 19:01 UTC, eschnett commented on TwoPuncturesX/schedule.ccl
> -    WRITES: ADMBaseX::metric(everywhere)
The change to `TwoPuncturesX` seems unrelated. It should not be necessary for this change to work.

2023-10-25 19:01 UTC, eschnett commented on Z4c/interface.ccl
> +USES INCLUDE HEADER: newradx.hxx
The list of include files should be sorted alphabetically.

2023-10-25 19:01 UTC, eschnett commented on Z4c/src/apply_newrad.cxx
> +  if (CCTK_Equals(boundary_conditions, "radiative")) {
It would be more efficient if this `if` statement was in the schedule. In this case, if one doesn't use radiative boundary conditions, this function does not need to be called.

2023-10-25 21:33 UTC, jaykalinani commented on Z4c/interface.ccl
> +USES INCLUDE HEADER: newradx.hxx
This comes from the `NewRadX` thorn. Should `NewRadX` be added under the required list of thorns?

2023-10-25 21:33 UTC, jaykalinani commented on Z4c/param.ccl
> -
Fixed.

2023-10-25 21:36 UTC, jaykalinani commented on Z4c/interface.ccl
Fixed. However, the following comment suggests arranging the header files alphabetically.  For now, I have added an empty line. Should I rather arrange everything alphabetically and remove the empty line?

2023-10-25 21:39 UTC, jaykalinani commented on Z4c/schedule.ccl
> +SCHEDULE Z4c_apply_boundary_conditions IN ODESolvers_RHS AFTER Z4c_RHS
Fixed. Current change reads "SCHEDULE Z4c_apply_boundary_conditions IN Z4c_RHSGroup AFTER Z4c_RHS. Hope this is okay.

2023-10-25 21:40 UTC, jaykalinani commented on Z4c/src/apply_newrad.cxx
> +using namespace Loop;
Fixed.

2023-10-25 21:40 UTC, jaykalinani commented on Z4c/src/apply_newrad.cxx
> +#include "cctk.h"
Fixed.

2023-10-25 21:40 UTC, jaykalinani commented on Z4c/param.ccl
> +  "none"      :: "use CarpetX default BCS"
Fixed.

2023-10-25 21:44 UTC, jaykalinani commented on TwoPuncturesX/schedule.ccl
> -    WRITES: ADMBaseX::metric(everywhere)
You are right, this is an unrelated change to Z4c boundary conditions. It was made because otherwise when running a simulation with `AsterX` and `Z4c`, and using `TwoPuncturesX` to set the initial data, I get an error that the metric is invalid at the boundaries. Thus, I changed the write statements to 'interior' and then applied sync. Do you have any better suggestions about this?

2023-10-25 21:45 UTC, jaykalinani commented on Z4c/interface.ccl
> +USES INCLUDE HEADER: newradx.hxx
The above comment suggested instead to add another line instead. Let me know if you prefer an additional line or all header files sorted alphabetically.

2023-10-25 21:45 UTC, jaykalinani commented on Z4c/src/apply_newrad.cxx
> +  if (CCTK_Equals(boundary_conditions, "radiative")) {
Fixed.

2023-10-26 13:42 UTC, eschnett commented on Z4c/interface.ccl
> +USES INCLUDE HEADER: newradx.hxx
This thorn `Z4c` will not compile unless `NewRadX` is present. So yes, `NewRadX` needs to be listed as required in `configuration.ccl`.

2023-10-26 13:44 UTC, eschnett commented on TwoPuncturesX/schedule.ccl
> -    WRITES: ADMBaseX::metric(everywhere)
The change to `TwoPuncturesX` seems necessary all the time, independent of this PR here.

You say you get an error. Why don't we see this error in our test cases? `TwoPuncturesX` sets its initial conditions on all grid points; why are you then seeing an error? It seems worthwhile to get to the bottom of this independent of this PR.

2023-10-26 13:46 UTC, eschnett commented
@jaykalinani Can you also add a test case for your changes? Remember that test cases should be small and fast. We don't need to do a convergence test – just a quick setup with a small grid running for 3 iterations would suffice.

2023-10-26 13:48 UTC, eschnett requested changes

2023-10-26 13:48 UTC, eschnett commented on Z4c/param.ccl
> +  "CarpetX"      :: "use CarpetX default boundary conditions"
Can you correct how the `::` are aligned?

2023-10-26 13:48 UTC, eschnett commented on Z4c/src/apply_newrad.cxx
> +extern "C" void Z4c_apply_boundary_conditions(CCTK_ARGUMENTS) {
This routine should be renamed to `apply_radiative_boundary_conditions` since that is what it now does.

2023-10-27 21:47 UTC, jaykalinani commented on Z4c/interface.ccl
> +USES INCLUDE HEADER: newradx.hxx
Fixed. This required adding `PROVIDES NewRadX` statement in the `configuration.ccl` of NewRadX thorn.

2023-10-27 21:48 UTC, jaykalinani commented on TwoPuncturesX/schedule.ccl
> -    WRITES: ADMBaseX::metric(everywhere)
Noted. I have reverted to the original file. Will dig in with the issue independently.

2023-10-27 21:49 UTC, jaykalinani commented
> @jaykalinani Can you also add a test case for your changes? Remember that test cases should be small and fast. We don't need to do a convergence test – just a quick setup with a small grid running for 3 iterations would suffice.

Added a test case based on `qc0` run.

2023-10-27 21:49 UTC, jaykalinani commented on Z4c/param.ccl
> +  "CarpetX"      :: "use CarpetX default boundary conditions"
Fixed.

2023-10-27 21:49 UTC, jaykalinani commented on Z4c/src/apply_newrad.cxx
> +extern "C" void Z4c_apply_boundary_conditions(CCTK_ARGUMENTS) {
Fixed.

2023-11-28 14:35 UTC, lucass-carneiro commented on NewRadX/configuration.ccl
Why `NewRadX` both provides and requires `NewRadX`? Shouldn't it be that it only provides?

2023-11-28 14:35 UTC, lucass-carneiro commented on Z4c/param.ccl
Suggestion: Use the parameter keyword `NewRadX` instead of `radiative`. It maybe indicates more explicitly that users are opting-in for a specific thorn to provide BCs

2023-11-28 14:35 UTC, lucass-carneiro commented on Z4c/schedule.ccl
> +  SYNC: chi_rhs
Are these explicit `SYNC` statements really necessary?

2023-11-28 14:35 UTC, lucass-carneiro commented on Z4c/src/apply_newrad.cxx
> +extern "C" void apply_boundary_conditions(CCTK_ARGUMENTS) {
Suggestion:

As far as I understand, when using `extern` in a function inside a `C++` namespace, that namespace is disregarded for linking purposes. That is `bar::foo()` is the same as `foo()` if `foo()` is declared with `extern "C"` as far as the linker is concerned. 

That means you cannot declare a `baz::foo()` function with C linkage because `foo` is already "taken"

When working with Cactus, what I (my personal opinion only) like to do is to have internal functions of a thorn inside a namespace and to name functions that are scheduled to Cactus with a prepended namespace name. In this case, I would prefer the function to be named `Z4c_apply_boundary_conditions`, which could internally call some function from the `Z4c` namespace or not.

It is unlikely that this thorn will have another function called `apply_boundary_conditions` that produces conflicts, so this is probably fine as is.

2023-11-28 14:35 UTC, lucass-carneiro commented on Z4c/src/apply_newrad.cxx
> +extern "C" void apply_boundary_conditions(CCTK_ARGUMENTS) {
Suggestion:

As far as I understand, when using `extern` in a function inside a `C++` namespace, that namespace is disregarded for linking purposes. That is `bar::foo()` is the same as `foo()` if `foo()` is declared with `extern "C"` as far as the linker is concerned. 

That means you cannot declare a `baz::foo()` function with C linkage because `foo` is already "taken"

When working with Cactus, what I (my personal opinion only) like to do is to have internal functions of a thorn inside a namespace and to name functions that are scheduled to Cactus with a prepended namespace name. In this case, I would prefer the function to be named `Z4c_apply_boundary_conditions`, which could internally call some function from the `Z4c` namespace or not.

It is unlikely that this thorn will have another function called `apply_boundary_conditions` that produces conflicts, so this is probably fine as is.

2023-11-28 14:35 UTC, lucass-carneiro commented on Z4c/src/apply_newrad.cxx
> +  NewRadX_Apply(cctkGH, chi, chi_rhs, 1, 1, 1);
This function should read the BC parameters from either `NewRadX` (preferably) or from a `Z4c` interface instead of hard coding them.

2023-11-28 14:35 UTC, lucass-carneiro commented on Z4c/test/test.ccl
According to @eschnett, these files are not "stable" yet and are not needed in tests. They should maybe be excluded from the commit.

2023-11-28 14:56 UTC, rhaas80 commented on NewRadX/configuration.ccl
Usually to have access to its own include files (true eg for ExternalLibraries that contains some test code). I don't think there is much use for this otherwise (unless you find any `#ifdef HAVE_CAPABILITY_NEWRADX` in the source code, which would admittedly be a bit strange).

2023-11-28 15:15 UTC, lwJi commented on NewRadX/configuration.ccl
I will remove `REQUIRES NewRadX` then

2023-11-28 15:18 UTC, lwJi commented on Z4c/param.ccl
Good point

2023-11-28 15:19 UTC, lwJi commented on Z4c/schedule.ccl
> +  SYNC: chi_rhs
Yes. Because this boundary condition requires information form its neighbor's rhs

2023-11-28 15:25 UTC, lwJi commented on Z4c/src/apply_newrad.cxx
> +extern "C" void apply_boundary_conditions(CCTK_ARGUMENTS) {
Didn't know that. Good point

2023-11-28 15:27 UTC, lwJi commented on Z4c/src/apply_newrad.cxx
> +  NewRadX_Apply(cctkGH, chi, chi_rhs, 1, 1, 1);
Yeah. That's just a quick try.

2023-11-28 15:51 UTC, jaykalinani commented on Z4c/src/apply_newrad.cxx
> +  NewRadX_Apply(cctkGH, chi, chi_rhs, 1, 1, 1);
The three parameters denote the value at infinity, the propagation speed and the exponent in radial fall-off. The first two parameter values should always remain the same for that particular grid-function. For the exponent of the radial fall-off, we have set (in our experience) the best choice, but have not made a complete parameter study. 

If a parameter is to be defined for this exponent, each grid function of `Z4c` (to which BCs are applied) would have its designated exponent parameter, to be defined in the `param.ccl` of `Z4c`. `NewRadX` should remain agnostic of the use of `Z4c` parameters. We can add these parameters to `Z4c` once you confirm.

2023-11-28 15:53 UTC, jaykalinani commented on Z4c/src/apply_newrad.cxx
> +extern "C" void apply_boundary_conditions(CCTK_ARGUMENTS) {
Indeed, I had initially defined the function name as `Z4c_apply_boundary_conditions` in my initial PR. @eschnett  asked me to change it to `apply_boundary_conditions`, which I did. Not sure how to address this..

2023-11-28 15:57 UTC, jaykalinani commented on Z4c/src/apply_newrad.cxx
> +extern "C" void Z4c_apply_boundary_conditions(CCTK_ARGUMENTS) {
@lucass-carneiro

2023-11-28 17:34 UTC, lucass-carneiro commented on Z4c/src/apply_newrad.cxx
> +extern "C" void apply_boundary_conditions(CCTK_ARGUMENTS) {
I think you can leave it as it is really. It is unlikely that a name clash will happen in this context. I was merely pointing out a suggestion, but I don't think anything "bad" will happen if it is left as it is

2023-11-28 17:39 UTC, lucass-carneiro commented on Z4c/src/apply_newrad.cxx
> +  NewRadX_Apply(cctkGH, chi, chi_rhs, 1, 1, 1);
Providing a way to control these in `Z4c` does indeed make more sense now that you pointed this out. I think it is unlikely that users will want to change these once optimal value are found, but still, it is always nice to give them a "chance" to do so.

2023-11-28 17:42 UTC, lwJi commented on Z4c/test/test.ccl
we will remove `test.ccl`

2023-11-28 19:20 UTC, jaykalinani commented on Z4c/src/apply_newrad.cxx
> +  NewRadX_Apply(cctkGH, chi, chi_rhs, 1, 1, 1);
Agreed! We will go ahead with the changes then. Thanks!

2023-11-28 19:21 UTC, jaykalinani commented on Z4c/src/apply_newrad.cxx
> +extern "C" void apply_boundary_conditions(CCTK_ARGUMENTS) {
We decided to go ahead with `Z4c_apply_NewRadX_boundary_conditions'. Thanks!

2023-11-28 20:27 UTC, merged