Z4c: fix bug in calc_dAu
EinsteinToolkit/SpacetimeX pull request #31
Opened 2024-07-09 16:01 UTC by lwJi

2024-07-09 17:20 UTC, eschnett requested changes

2024-07-09 17:20 UTC, eschnett commented on Z4c/src/physics.hxx
>        return sum<D>([&](int x) ARITH_INLINE {
I recommend calling `sum_symm<D>` to perform a symmetric sum over two indices:

```
sum_symm<D>([&](int x, int y) { 
    return dgu(a, x)(c) * gu(b, y) * A(x, y)   //
                 + gu(a, x) * dgu(b, y)(c) * A(x, y) //
                 + gu(a, x) * gu(b, y) * dA(x, y)(c);
...
```

2024-07-09 17:28 UTC, lwJi commented on Z4c/src/physics.hxx
>        return sum<D>([&](int x) ARITH_INLINE {
Make sense. Done.

2024-07-10 14:22 UTC, eschnett approved these changes

2024-07-10 15:24 UTC, merged